server:
  port: 8081

spring:
  application:
    name: nas-hc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://dy.com:3306/d_nas_hc?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: test@123
    hikari:
      pool-name: nas-hc-pool
      #最小空闲连接数 <类似于线程池的核心线程数>
      minimum-idle: 5
      #最大连接数 <类似于线程池的最大线程数>
      maximum-pool-size: 20
      # 监控
      register-mbeans: true

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleteFlag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

