server:
  port: 8111

spring:
  application:
    name: nas-cloud-canal
  #Redis 配置
  redis:
    # Redis服务器地址
    host: dy.com
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: test@123
    # 链接超时时间 单位 ms（毫秒）
    timeout: 3000
    # Redis 线程池设置
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 3000
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: dy.com:8848
        username: nacos
        password: nacos

management:
  endpoints:
    web:
      exposure:
        include: '*'
