server:
  port: 8111


#开发环境
env:
  host: ds.com

spring:
  application:
    name: nas-cloud-canal
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: ${env.host}:8848
        username: nacos
        password: nacos
  kafka:
    bootstrap-servers: ${env.host}:9092
    producer: # 生产者
      retries: 3 # 设置大于0的值，则客户端会将发送失败的记录重新发送
      batch-size: 16384
      buffer-memory: 33554432
      acks: 1
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
