server:
  port: 9001

#开发环境
env:
  host: dy.com

spring:
  application:
    name: nas-gateway
  #Redis 配置
  redis:
    # Redis服务器地址
    host: ${env.host}
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: msj@ks12d3
    # 链接超时时间 单位 ms（毫秒）
    timeout: 3000
    # Redis 线程池设置
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 3000
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
  kafka:
    bootstrap-servers: ${env.host}:9092
    producer: # 生产者
      retries: 3 # 设置大于0的值，则客户端会将发送失败的记录重新发送
      batch-size: 16384
      buffer-memory: 33554432
      acks: 1
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: gid-gateway
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      # 手动调用Acknowledgment.acknowledge()后立即提交，一般使用这种
      # MANUAL_IMMEDIATE
      ack-mode: manual_immediate
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: ${env.host}:8848
        username: nacos
        password: nacos
    #sentinel
    sentinel:
      transport:
        port: ${server.port}
        dashboard: ${env.host}:8800
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        # hc
        - id: nas-hc-route
          uri: lb://nas-hc
          predicates:
            - Path=/api/hc/**
          filters:
            - StripPrefix=2
        # nat
        - id: nas-nat-route
          uri: lb://nas-nat
          predicates:
            - Path=/api/nat/**
          filters:
            - StripPrefix=2
  # json 时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

management:
  endpoints:
    web:
      exposure:
        include: '*'
