server:
  port: 8121

#开发环境
env:
  host: ds.com

spring:
  application:
    name: nas-cloud-batch
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: ${env.host}:8848
        username: nacos
        password: nacos

xxl:
  job:
    accessToken: uc834JPL1DB5uH4
    admin:
      addresses: http://localhost:8080/xxl-job-admin
    executor:
      address:
      appname: ${spring.application.name}
      ip:
      logpath:
      logretentiondays: 30
      port: 9999
