server:
  port: 9121

#开发环境
env:
  host: ds.com

spring:
  application:
    name: nas-cloud-batch
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: ${env.host}:8848
        username: nacos
        password: nacos

xxl:
  job:
    accessToken: default_token
    admin:
      addresses: http://${env.host}:8080/xxl-job-admin
    executor:
      address:
      appname: ${spring.application.name}
      ip:
      logpath:
      logretentiondays: 3
      port: 9999

